// Watch/production build, in the shape of obsidianmd/obsidian-sample-plugin's esbuild.config.mjs:
// `node esbuild.config.mjs` watches, `node esbuild.config.mjs production` builds once and exits.
//
// Adaptations, all forced by what this plugin bundles:
//   - platform "node": core spawns child processes and touches the filesystem.
//   - node builtins are external, not just the sample's CodeMirror/electron list.
//   - the import.meta.url banner below.
//   - no minify: deliberately out of scope while the bundle ships as a release asset.
//   - the OBSIDIAN_PLUGIN_DIR delivery step below.
import { builtinModules } from "node:module";
import { copyFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";
import esbuild from "esbuild";
import { thirdPartyLicenses } from "./third-party-licenses.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const nodeBuiltins = [...new Set(builtinModules.flatMap((name) => [name, `node:${name}`]))];
const prod = process.argv[2] === "production";

/**
 * Obsidian loads a plugin only from `<vault>/.obsidian/plugins/<id>/`, so a repository kept
 * outside the vault has to deliver its build there. That is the outside-the-vault workflow
 * obsidian-sample-plugin's README documents — copy `main.js`, `manifest.json` and
 * `styles.css` across — automated here so a watch rebuild lands in the vault without a
 * second command.
 *
 * The build still writes `main.js` at the repository root and copies from there rather than
 * pointing `outfile` at the vault: the bundle-load test resolves it from the root and fails if
 * it is missing or stale, and releases attach that same file. Unset, nothing is copied and the
 * build behaves as it always has.
 */
const vaultPluginDirectory = process.env.OBSIDIAN_PLUGIN_DIR;

const deliverToVault = {
  name: "deliver-to-vault",
  setup(build) {
    if (vaultPluginDirectory === undefined || vaultPluginDirectory.length === 0) return;
    const target = resolve(vaultPluginDirectory);
    build.onEnd(async (result) => {
      // Leave the last good build in place when a rebuild fails, so Obsidian keeps running
      // something that loads instead of a half-written bundle.
      if (result.errors.length > 0) return;
      await mkdir(target, { recursive: true });
      for (const file of ["main.js", "manifest.json", "styles.css"]) {
        await copyFile(file, resolve(target, file));
      }
      console.log(`delivered main.js, manifest.json and styles.css to ${target}`);
    });
  },
};

const context = await esbuild.context({
  entryPoints: ["main.ts"],
  outfile: "main.js",
  bundle: true,
  platform: "node",
  target: "node18",
  format: "cjs",
  treeShaking: true,
  // Watch builds get an inline sourcemap; production does not. The sourcemap is 9.4 MB of a
  // 12.7 MB bundle, and Obsidian Sync refuses to sync a file over 5 MB — with it, every user
  // syncing a vault silently stops receiving plugin updates. Without it the bundle is 3.3 MB.
  // Debuggability survives: this build does not minify, so a production stack trace still
  // carries real function names, just not original line numbers.
  //
  // An earlier comment here claimed prod had to match watch because "the bundle-load test
  // asserts a recorded byte baseline". No such assertion exists, in that test or any other --
  // plugin-bundle.test.ts stats main.js for its mtime, to check freshness, never its size.
  sourcemap: prod ? false : "inline",
  // The Claude Agent SDK is ESM. Bundled into CJS, esbuild shims `import.meta` as an
  // empty object, so the SDK's `createRequire(import.meta.url)` receives undefined and
  // the plugin throws on load. Point it at a real file URL derived from __filename.
  define: { "import.meta.url": "__shorthandImportMetaUrl" },
  banner: {
    js: `${banner}const __shorthandImportMetaUrl = require('node:url').pathToFileURL(__filename).href;`,
  },
  external: ["obsidian", "electron", ...nodeBuiltins],
  // The marketplace installs only main.js, manifest.json and styles.css. Embed dependency
  // licenses into main.js before deliver-to-vault copies it, so the artifact users actually
  // receive carries the notices required by the code bundled into it. The notice plugin reads
  // the metafile and fails a build when any included package has no reviewed license source.
  metafile: true,
  plugins: [thirdPartyLicenses, deliverToVault],
  logLevel: "info",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
