// Watch/production build, in the shape of obsidianmd/obsidian-sample-plugin's esbuild.config.mjs:
// `node esbuild.config.mjs` watches, `node esbuild.config.mjs production` builds once and exits.
//
// Adaptations, all forced by what this plugin bundles:
//   - platform "node": core spawns child processes and touches the filesystem.
//   - node builtins are external, not just the sample's CodeMirror/electron list.
//   - the import.meta.url banner below.
//   - no minify: deliberately out of scope while the bundle ships as a release asset.
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const nodeBuiltins = [...new Set(builtinModules.flatMap((name) => [name, `node:${name}`]))];
const prod = process.argv[2] === "production";

const context = await esbuild.context({
  entryPoints: ["main.ts"],
  outfile: "main.js",
  bundle: true,
  platform: "node",
  target: "node18",
  format: "cjs",
  treeShaking: true,
  // Inline in production too, unlike the sample. The bundle-load test asserts a recorded
  // byte baseline; dropping the sourcemap only in prod would make that baseline mean two
  // different things depending on which script produced main.js.
  sourcemap: "inline",
  // The Claude Agent SDK is ESM. Bundled into CJS, esbuild shims `import.meta` as an
  // empty object, so the SDK's `createRequire(import.meta.url)` receives undefined and
  // the plugin throws on load. Point it at a real file URL derived from __filename.
  define: { "import.meta.url": "__handyImportMetaUrl" },
  banner: {
    js: `${banner}const __handyImportMetaUrl = require('node:url').pathToFileURL(__filename).href;`,
  },
  external: ["obsidian", "electron", ...nodeBuiltins],
  logLevel: "info",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
